language: java
jdk:
  - oraclejdk8
before_install:
  - sudo add-apt-repository ppa:duggan/bats --yes
  - sudo apt-get update -qq
  - sudo apt-get install -qq bats
  - sudo apt-get install build-essential
  - mkdir protobuf_install
  - pushd protobuf_install
  - wget http://protobuf.googlecode.com/files/protobuf-2.5.0.tar.gz
  - tar xzf protobuf-2.5.0.tar.gz
  - cd  protobuf-2.5.0
  - ./configure
  - make
  - sudo make install
  - sudo ldconfig
  - protoc --version
  - popd
  - pwd
  - test $(uname) = "Linux" && sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test || true
  - test $(uname) = "Linux" && sudo add-apt-repository -y ppa:george-edison55/cmake-3.x || true
  - test $(uname) = "Linux" && sudo add-apt-repository -y 'deb http://llvm.org/apt/trusty/ llvm-toolchain-trusty-3.8 main' || true
  - test $(uname) = "Linux" && sudo add-apt-repository -y 'deb http://llvm.org/apt/trusty/ llvm-toolchain-trusty-3.9 main' || true
  - test $(uname) = "Linux" && wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key | sudo apt-key add - || true
  - test $(uname) = "Linux" && sudo apt-get update -y || true
  - test $(uname) = "Linux" && sudo apt-get install -qq -y g++-4.9 g++-5 g++-6 clang-3.8 clang-3.9 cmake cmake-data zlib1g-dev libbz2-dev || true
build: ./start-build-env.sh
